batch_size: 512
context_len: 20
cut: 0
dataset: Datas
dataset_dir: data/
device: cuda:6
dropout_p: 0.1
embed_dim: 128
log_dir: ADAPT_runs/
lr: 0.0001
max_eval_ep_len: 1001
model_dir: 
n_blocks: 6
n_epochs_ref: 1
n_heads: 1
position_encoding_length: 40
num_eval_ep: 1024
seed: 88
warmup_steps: 10000
wt_decay: 0.005
algorithm_name: ADAPT
task: a1_amp
note: Teacher from AMP
wandboff: False
state_dim: 48
act_dim: 12
body_dim: 12
